---
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  required:
    ':development':
      - gem: 'puppet-lint-absolute_template_path'
        version: '~> 1.0'
      - gem: 'puppet-lint-empty_string-check'
        version: '~> 0.2'
      - gem: 'puppet-lint-leading_zero-check'
        version: '~> 0.1'
      - gem: 'puppet-lint-legacy_facts-check'
        version: '~> 1.0'
      - gem: 'puppet-lint-resource_reference_syntax'
        version: '~> 1.0'
      - gem: 'puppet-lint-spaceship_operator_without_tag-check'
        version: '~> 0.1'
      - gem: 'puppet-lint-top_scope_facts-check'
        version: '~> 1.0'
      - gem: 'puppet-lint-trailing_comma-check'
        version: '~> 0.4'
      - gem: 'puppet-lint-trailing_newline-check'
        version: '~> 1.1'
      - gem: 'puppet-lint-undef_in_function-check'
        version: '~> 0.2'
      - gem: 'puppet-lint-unquoted_string-check'
        version: '~> 0.3'
      - gem: 'puppet-lint-variable_contains_upcase'
        version: '~> 1.2'
      - gem: 'puppet-lint-version_comparison-check'
        version: '~> 0.2'
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
      - gem: 'coveralls'
Rakefile:
  requires:
    - 'puppet-strings/tasks'
spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
